from .shortcuts import shortcuts_duplicate
from .shortcuts import shortcuts_copy
from .shortcuts import shortcuts_paste
from .shortcuts import shortcuts_delete
from .shortcuts import shortcuts_lock
from .shortcuts import shortcuts_unlock 
from .shortcuts import shortcuts_group 
from .shortcuts import shortcuts_ungroup
from .shortcuts import shortcuts_bring_to_front 
from .shortcuts import shortcuts_bring_to_front 
from .shortcuts import shortcuts_send_to_back
from .shortcuts import shortcuts_undo  
from .shortcuts import shortcuts_redo 
from .shortcuts import shortcuts_select_all 